version: "3.8"

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./sql-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    ports:
      - "3396:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: SiteUsers
      MYSQL_PASSWORD: password
    networks:
      - mysql-phpmyadmin

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - mysql-phpmyadmin

  backend:
    build: ./GO
    container_name: go-backend
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: SiteUsers
    restart: always
    depends_on:
      - db
    networks:
      - mysql-phpmyadmin

networks:
  mysql-phpmyadmin:

volumes:
  db_data:
